In [14]:
import pandas as pd

# Cargar dataset
df = pd.read_csv("../data/raw/vulnerability_fix_dataset.csv")

print(df.shape)
df.head()

(35000, 3)

,vulnerability_type,vulnerable_code,fixed_code
0,SQL Injection,import java.sql.*;\n\npublic class SQLInjectio...,import java.sql.*;\n\npublic class SQLInjectio...
1,SQL Injection,import java.sql.*;\n\npublic class VulnerableS...,import java.sql.*;\n\npublic class SecureSQLIn...
2,SQL Injection,import java.sql.*;\n\npublic class SQLInjectio...,To prevent SQL Injection attacks in the provid...
3,SQL Injection,import java.sql.Connection;\nimport java.sql.D...,To fix the SQL Injection vulnerability in the ...
4,SQL Injection,import java.sql.*;\n\npublic class VulnerableC...,import java.sql.*;\n\npublic class SecureCode ...

Verificar duplicados:

In [15]:
duplicados = df.duplicated().sum()

print(f"Duplicados encontrados: {duplicados}")

Duplicados encontrados: 2517

# Tercera celda

Eliminar duplicados:

In [16]:
df = df.drop_duplicates()

print(df.shape)

(32483, 3)

# Cuarta celda

Eliminar registros donde fixed_code sea explicación en inglés.

In [17]:
patrones_texto = [
    "To fix",
    "Here's",
    "Here is",
    "You should",
    "One way",
    "To prevent"
]

mask = df["fixed_code"].astype(str).str.startswith(tuple(patrones_texto))

print("Registros a eliminar:", mask.sum())

df = df[~mask]

Registros a eliminar: 11395

# Quinta celda

Crear dataset binario.

In [18]:
vulnerables = pd.DataFrame({
    "code": df["vulnerable_code"],
    "label": 1
})

seguros = pd.DataFrame({
    "code": df["fixed_code"],
    "label": 0
})

# Sexta celda

Unir ambos datasets:

In [19]:
security_dataset = pd.concat(
    [vulnerables, seguros],
    ignore_index=True
)

security_dataset.head()

                                                code  label
0  import java.sql.*;\n\npublic class SQLInjectio...      1
1  import java.sql.*;\n\npublic class VulnerableS...      1
2  import java.sql.*;\n\npublic class VulnerableC...      1
3  import java.sql.*;\n\npublic class SQLInjectio...      1
4  import java.sql.Connection;\nimport java.sql.D...      1

# Séptima celda

Mezclar aleatoriamente:

In [20]:
security_dataset = security_dataset.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# Octava celda

Verificar balance:

In [21]:
security_dataset["label"].value_counts()

label
0    21088
1    21088
Name: count, dtype: int64

# Novena celda

Guardar resultado:

In [22]:
security_dataset.to_csv(
    "../data/processed/security_dataset.csv",
    index=False
)

print("Dataset guardado correctamente")

Dataset guardado correctamente

In [23]:
security_dataset.shape

security_dataset["label"].value_counts()

label
0    21088
1    21088
Name: count, dtype: int64

In [24]:
print(security_dataset.shape)

security_dataset.sample(5)

(42176, 2)

                                                    code  label
30878  import java.io.File;\nimport java.io.FileWrite...      0
10242  import java.io.*;\nimport javax.servlet.*;\nim...      1
1830   import java.io.*;\nimport javax.servlet.*;\nim...      0
16789  import java.sql.Connection;\nimport java.sql.D...      0
2122   import java.util.Scanner;\n\npublic class Buff...      1

In [25]:
security_dataset["code"].isna().sum()

np.int64(0)

In [26]:
print(list(df.columns))
df.head()

['vulnerability_type', 'vulnerable_code', 'fixed_code']

,vulnerability_type,vulnerable_code,fixed_code
0,SQL Injection,import java.sql.*;\n\npublic class SQLInjectio...,import java.sql.*;\n\npublic class SQLInjectio...
1,SQL Injection,import java.sql.*;\n\npublic class VulnerableS...,import java.sql.*;\n\npublic class SecureSQLIn...
4,SQL Injection,import java.sql.*;\n\npublic class VulnerableC...,import java.sql.*;\n\npublic class SecureCode ...
5,SQL Injection,import java.sql.*;\n\npublic class SQLInjectio...,import java.sql.*;\n\npublic class SecureSQLIn...
6,SQL Injection,import java.sql.Connection;\nimport java.sql.D...,import java.sql.Connection;\nimport java.sql.D...